# Multiple Variable Linear Regression

In [1]:
import copy, math
import numpy as np
import matplotlib.pyplot as plt

In [2]:
X_train = np.array([[10, 4, 4, 10], [20, 5, 5, 10], [30, 6, 6, 10]])    # [[1, 5, 1, 45], [2, 3, 2, 40], [3, 2, 1, 35]
y_train = np.array([1000, 2000, 3000])

In [3]:
print(f"X Shape: {X_train.shape}")
print(X_train)
print(f"y Shape: {y_train.shape}")
print(y_train)

X Shape: (3, 4)
[[10  4  4 10]
 [20  5  5 10]
 [30  6  6 10]]
y Shape: (3,)
[1000 2000 3000]


In [4]:
def cost(x, y, w, b):
    m = x.shape[0]
    co = 0
    for i in range(m):
        fwb = np.dot(x[i],w) + b
        co = co + (fwb - y[i])**2
    co = co / (2 * m)
    return co

In [5]:
def gradient(x, y, w, b):
    m,n = x.shape
    
    dw = np.zeros(n)
    db = 0
    
    for i in range(m):
        
        f =  (np.dot(x[i],w) + b) - y[i]
        
        for j in range(n):
            
            dw[j] = dw[j] + f * x[i,j]
        db = db + f 
        
    dw = dw / m
    db = db / m
    
    return dw,db
    
    

In [6]:
def gradient_descent(x, y, w, b, iterations, alpha):
    
    
    for i in range(iterations):
        
        dw, db = gradient(x, y, w, b)
        
        w = w - alpha * dw
        b = b - alpha * db
    
        c = cost(x, y, w, b)
        print(f"Iteration {i:4d}: Cost {c:8.2f}   ")
    
    return w, b, c

In [8]:
# initialize parameters
init_w = np.zeros_like(X_train[0])
init_b = 0
# some gradient descent settings
iterations = 850
alpha = 0.001
# run gradient descent 
w_final, b_final,c = gradient_descent(X_train, y_train, init_w, init_b, iterations, alpha)
print(f"b,w found by gradient descent: {b_final:0.2f},{w_final} ")

Iteration    0: Cost 374663.33   
Iteration    1: Cost 69798.48   
Iteration    2: Cost 22089.98   
Iteration    3: Cost 14374.47   
Iteration    4: Cost 12885.29   
Iteration    5: Cost 12371.89   
Iteration    6: Cost 12017.68   
Iteration    7: Cost 11695.48   
Iteration    8: Cost 11385.33   
Iteration    9: Cost 11083.93   
Iteration   10: Cost 10790.59   
Iteration   11: Cost 10505.03   
Iteration   12: Cost 10227.03   
Iteration   13: Cost  9956.38   
Iteration   14: Cost  9692.90   
Iteration   15: Cost  9436.39   
Iteration   16: Cost  9186.67   
Iteration   17: Cost  8943.55   
Iteration   18: Cost  8706.87   
Iteration   19: Cost  8476.46   
Iteration   20: Cost  8252.14   
Iteration   21: Cost  8033.76   
Iteration   22: Cost  7821.15   
Iteration   23: Cost  7614.18   
Iteration   24: Cost  7412.68   
Iteration   25: Cost  7216.51   
Iteration   26: Cost  7025.53   
Iteration   27: Cost  6839.61   
Iteration   28: Cost  6658.61   
Iteration   29: Cost  6482.40   
Iteration

# Prediction

In [9]:
print(f"prediction: {np.dot(X_train[0], w_final) + b_final:0.2f}, target value: {y_train[0]}")

prediction: 1000.00, target value: 1000


### **** Predicting House Price having ( 40 square feet size, 7 Bedrooms , 7 bathrooms and 10 year old  ) ***

In [10]:
x_house = np.array([40, 7, 7, 10])  

In [11]:
def predict(x, w, b): 
    p = np.dot(x, w) + b     
    return p    

In [12]:
res = predict(w_final,x_house,b_final)

In [13]:
print("$",res)

$ 3999.9961253667257
