# Regularized Cost and Gradient for linear regression

In [1]:
import copy, math
import numpy as np
import matplotlib.pyplot as plt

In [2]:
X_train = np.array([[10, 4, 4, 10], [20, 5, 5, 10], [30, 6, 6, 10]])    
y_train = np.array([1000, 2000, 3000])

In [3]:
print(f"X Shape: {X_train.shape}")
print(X_train)
print(f"y Shape: {y_train.shape}")
print(y_train)

X Shape: (3, 4)
[[10  4  4 10]
 [20  5  5 10]
 [30  6  6 10]]
y Shape: (3,)
[1000 2000 3000]


In [4]:
def cost(x, y, w, b, lambda_r):
    m = x.shape[0]
    n  = len(w)
    co = 0
    for i in range(m):
        fwb = np.dot(x[i],w) + b
        co = co + (fwb - y[i])**2
    co = co / (2 * m)
    
    reg_cost = 0
    for j in range(n):
        reg_cost = reg_cost + (w[j]**2)                                          
    reg_cost = (lambda_r / (2 * m)) * reg_cost                              
    
    total_cost = co + reg_cost                                   
    return total_cost    

In [5]:
def gradient(x, y, w, b,lambda_r):
    m,n = x.shape
    
    dw = np.zeros(n)
    db = 0
    
    for i in range(m):
        
        f =  (np.dot(x[i],w) + b) - y[i]
        
        for j in range(n):
            
            dw[j] = dw[j] + f * x[i,j]
        db = db + f 
        
    dw = dw / m
    db = db / m
    
    for j in range(n):
        dw[j] = dw[j] + (lambda_r / m) * w[j]

    
    return dw,db
    
    

In [6]:
def gradient_descent(x, y, w, b, iterations, alpha, lambda_r):
    
    
    for i in range(iterations):
        
        dw, db = gradient(x, y, w, b, lambda_r)
        
        w = w - alpha * dw
        b = b - alpha * db
    
        c = cost(x, y, w, b, lambda_r)
        print(f"Iteration {i:4d}: Cost {c:8.2f}   ")
    
    return w, b, c

In [7]:
# initialize parameters
init_w = np.zeros_like(X_train[0])
init_b = 0
# some gradient descent settings
iterations = 500
alpha = 0.001
lambda_r = 1
# run gradient descent 
w_final, b_final,c = gradient_descent(X_train, y_train, init_w, init_b, iterations, alpha, lambda_r)
print(f"b,w found by gradient descent: {b_final:0.2f},{w_final} ")

Iteration    0: Cost 375130.89   
Iteration    1: Cost 70852.82   
Iteration    2: Cost 23315.89   
Iteration    3: Cost 15640.21   
Iteration    4: Cost 14160.09   
Iteration    5: Cost 13649.52   
Iteration    6: Cost 13297.05   
Iteration    7: Cost 12976.54   
Iteration    8: Cost 12668.20   
Iteration    9: Cost 12368.76   
Iteration   10: Cost 12077.52   
Iteration   11: Cost 11794.20   
Iteration   12: Cost 11518.55   
Iteration   13: Cost 11250.39   
Iteration   14: Cost 10989.49   
Iteration   15: Cost 10735.67   
Iteration   16: Cost 10488.73   
Iteration   17: Cost 10248.49   
Iteration   18: Cost 10014.77   
Iteration   19: Cost  9787.38   
Iteration   20: Cost  9566.15   
Iteration   21: Cost  9350.93   
Iteration   22: Cost  9141.54   
Iteration   23: Cost  8937.83   
Iteration   24: Cost  8739.65   
Iteration   25: Cost  8546.84   
Iteration   26: Cost  8359.25   
Iteration   27: Cost  8176.76   
Iteration   28: Cost  7999.21   
Iteration   29: Cost  7826.48   
Iteration

# Prediction

In [8]:
print(f"prediction: {np.dot(X_train[0], w_final) + b_final:0.2f}, target value: {y_train[0]}")

prediction: 1005.67, target value: 1000


### **** Predicting House Price having ( 40 square feet size, 7 Bedrooms , 7 bathrooms and 10 year old  ) ***

In [9]:
x_house = np.array([40, 7, 7, 10])  

In [10]:
def predict(x, w, b): 
    p = np.dot(x, w) + b     
    return p    

In [11]:
res = predict(w_final,x_house,b_final)

In [12]:
print("$",res)

$ 3989.2089349149887
